version: '3.8'

services:
  web:
    build:
      context: ./src
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.4.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: restaurant_app
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
