# PHP için Dockerfile
FROM php:8.0-apache

# Apache modüllerini etkinleştirme
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Uygulama dosyalarını konteynıra kopyala
COPY ./src/ /var/www/html/

# Apache yazma izinlerini düzenleme
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Port aç
EXPOSE 80
